### ISSUE TITLE
SSLDecoder website broken due to expired/invalid certificate

### ISSUE THREAD

**Issue by MyIsaak** [website-checks/website-checks#74]
Currently two test results are failing which are from SSLDecoder website maintained by @DanielRuf. To fix the CI builds I've extracted the two tests inside a test branch `fix-ssldecoder`, to keep the main branch healthy until an external fix from the host is performed.

**Comment by DanielRuf** [comment]
The certificate did not expire in fact, this is the default certificate from my hosting provider which is used when a subdomain doesn't exist anymore (selfsigned by kasserver / All Inkl) =)

See my comments here regarding the outdated ssldecoder project: https://github.com/website-checks/website-checks/commit/6887ebb74f132b941ce9438c6e10437eba82a013#r55605074

https://raymii.org/s/blog/Cancellation_notice_for_cipherlist_ssldecoder_and_certificatemonitor.html

I maintained a fork of the sslcoder project but stopped hosting it after some time.

**Comment by DanielRuf** [comment]
> until an external fix from the host is performed.

There will be no fix from the host side since the subdomain doesn't exist anymore and the uberspace account was closed ;-)

You can get the same certificate warning with https://anything-that-does-not-exist.daniel-ruf.de to get the selfsigned cert from the hosting provider =)

<img width="626" alt="Bildschirmfoto 2021-08-29 um 14 44 54" src="https://user-images.githubusercontent.com/827205/131250778-dd0df941-7b5b-40e1-9cb1-a2ad77c4d46d.png">
<img width="377" alt="Bildschirmfoto 2021-08-29 um 14 45 03" src="https://user-images.githubusercontent.com/827205/131250780-13b8f321-6ab9-437b-ba8c-fc672f33eda2.png">

SSL_ERROR_BAD_CERT_DOMAIN means that the subject and alternative names do not match the current hostname.

I think you can delete the branch with the extracted tests. Or what do you think?

**Comment by MyIsaak** [comment]
> The certificate did not expire in fact, this is the default certificate from my hosting provider which is used when a subdomain doesn't exist anymore (selfsigned by kasserver / All Inkl) =)

I had assumed it had expired, since it's a typical mistake. Anyways, returning a self signed certificate IMO a bit misleading. One could think it's a Man in the Middle Attack or something else.. Perhaps a 404 would be nicer :)

> I think you can delete the branch with the extracted tests. Or what do you think?

Since we still have httpobservatory.js which basically does better than ssldecoder I think it's not such a loss to delete the branch. If we ever need it back, it will still stay in commit history.

**Comment by DanielRuf** [comment]
> I had assumed it had expired, since it's a typical mistake. Anyways, returning a self signed certificate IMO a bit misleading. One could think it's a Man in the Middle Attack or something else.. Perhaps a 404 would be nicer :)

I can't do much there since this is the certificate that my hosting provider uses when the subdomain does not exist or is not configured with a LetsEncrypt certificate.

Since I have applied HSTS on all subdomains (otherwise my domain would be rejected for the HSTS preload list in the browsers, see the requirements at https://hstspreload.org/), the browsers correctly block the access and tell you, that it is not secure due to the subject name mismatch.

There should be a text passage with "HSTS" mentioned when you try to open any of those subdomains on my domain, that do not exists.

Before the subdomain was deleted there was a "this account is closed" message from uberspace, similar to a 404.
